[package]
name = "pxros-hr"
version = "0.1.0"
authors = ["HighTec EDV-Systeme GmbH - info@hightec-rt.com"]
description = "PXROS-HR v8.2.0 tc3xx Evaluation Version"
repository = "https://github.com/hightec-rt/pxros-hr"
edition = "2021"
license = "LICENSES"